# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number
    gym(
      scheme: "Release"
    )
    upload_to_app_store

    version = get_version_number(
      xcodeproj: "wkwktodo.xcodeproj",
      target: "wkwktodo"
    )
    message = "Release wkwktodo #{version}"
    push_to_slack(message: message)
    git_commit(path: ".", message: message)
    push_to_git_remote(
      remote: "origin",
      local_branch: "develop",
      remote_branch: "develop"
    )
  end

  private lane :push_to_slack do |options|
    slack(
      message: options[:message]
    )
  end
end

error do |lane, exception|
  slack(
    message: exception.to_s,
    success: false,
    payload: { "Output" => exception.error_info.to_s }
  )
end
